### ISSUE TITLE
Is this compatible with mongodb?

### ISSUE THREAD

**Issue by moazam1** [mateusjunges/laravel-acl#153]
Hi, curious if this package is compatible with mongodb? Thanks

**Comment by mateusjunges** [comment]
I never used laravel with MongoDB, so i can't answer your question now. I'll create a fresh laravel install tonight and check if this package work well.

**Comment by moazam1** [comment]
thank you!

**Comment by mateusjunges** [comment]
@moazam1 sorry for my late response.
I think we can't use it with MongoDB, since laravel relations works different way with mongodb. ATM, i can't find any work around for that.
I tried to replace the package models with new ones, extending `Jenssegers\Mongodb\Eloquent\Model` (as explained in [jessengers/mongodb][1] docs), but it does not work.

[1]: https://github.com/jenssegers/laravel-mongodb
