### ISSUE TITLE
Exception at UsersTrait:200 when revokingGroup from User

### ISSUE THREAD

**Issue by VegaTom** [mateusjunges/laravel-acl#154]
When trying to revoke groups from user by passing an array of slugs there is an exception (notice) and group isnt revoked:
 ```
$user->revokeGroup(['petty-cash-user'])
PHP Notice:  Trying to get property 'id' of non-object in D:/Proyectos/software/vendor/mateusjunges/laravel-acl/src/Traits/UsersTrait.php on line 200
```
![image](https://user-images.githubusercontent.com/25960724/69171717-7a50ab00-0aca-11ea-95ac-9abcfdca8a54.png)

Line 200 should be return $_group->id instead of return $group->id;
![image](https://user-images.githubusercontent.com/25960724/69171915-d61b3400-0aca-11ea-94fe-53da39a350eb.png)

**Comment by mateusjunges** [comment]
@VegaTom thanks for your report. Feel free to send a PR to fix it. Otherwise, i'll do it as soon as i came home.

**Comment by VegaTom** [comment]
No worries, i will w8. :)

**Comment by mateusjunges** [comment]
@VegaTom Which version of this package are you using? (Check in your `composer.json` file).
This bug has been fixed with the release `2.0.0`.
Check it here:
https://github.com/mateusjunges/laravel-acl/blob/cf43e31457194cfcd2a55883cfeb9957b028eec4/src/Traits/UsersTrait.php#L207

To upgrade your package to the last version, change the version in your `composer.json` file and run `composer update`.

This is the last release: 
```json
{
    "require": {
        "mateusjunges/laravel-acl": "2.2.*"
    }
}
```

If you are using a laravel version below 5.5, use the `2.0.*` version for laravel ACL:
```json
{
    "require": {
        "mateusjunges/laravel-acl": "2.0.*"
    }
}
```

**Comment by VegaTom** [comment]
didnt realice i was using 1.8. Thanks :)

**Comment by mateusjunges** [comment]
Glad that i can help you :)
