### ISSUE TITLE
How to customize Models to Admin

### ISSUE THREAD

**Issue by keatwei** [mateusjunges/laravel-acl#169]
I have 2 logins (User and Admin)
How do I customize the package to use Admin model?

**Comment by mateusjunges** [comment]
@keatwei The documentation about replacing and extending this package models [can be found here][1]. I don't know if you are adding this package to a fresh laravel installation or an existing one, but if it is a fresh installation, isn't it better to have to groups, `users` ans `admins`, instead of having a login system for each one?

BTW, you can find the [laravel docs][laravel-docs] about guards [here][2]. It allows you to login users in different `guards`, like `admin` and `user`.


[1]: https://mateusjunges.github.io/laravel-acl/guide/usage.html#extending-and-replacing-models
[2]: https://laravel.com/docs/7.x/authentication#adding-custom-guards
[laravel-docs]: https://laravel.com/docs

**Comment by mateusjunges** [comment]
@keatwei any updates on this?

**Comment by mateusjunges** [comment]
I'm closing this due to lack of feedback.
