### ISSUE TITLE
Documetation Link broken with 404 Error

### ISSUE THREAD

**Issue by DennisBrieske** [mateusjunges/laravel-acl#240]
Hey Mateus,

i think anything is wrong with Documentation Link: https://mateusjunges.github.io/laravel-acl/
It produce a 404 Error "Filenot Found"

Best greetings
Dennis

**Comment by mateusjunges** [comment]
Hi @DennisBrieske 
thanks for letting me know. I'm making some adjustments in the master branch because the next major version will be documented in my personal website, so i removed some files from the docs folder in that branch. I updated the gh pages configuration to be built from the `3.x` instead of `master`. It should be ok now.
