### ISSUE TITLE
Is there a way to upgrade a L9 app to L10? - "If you are using v3, do not upgrade to v4. Use it in new projects only"

### ISSUE THREAD

**Issue by ok200paul** [mateusjunges/laravel-acl#265]
Hey Mateus, 

Thanks for your work over the years on this package, it has done a great job for our needs.

**Describe the bug**
Is there a way to upgrade an L9 version to L10? In [this issue](https://github.com/mateusjunges/laravel-acl/issues/253) you say "If you are using v3, do not upgrade to v4. Use it in new projects only". 

It looks like the DB schema is a lot different for v4, and there's no upgrade documentation to go from v3 of the package to v4.

It also looks like there's been no commits for almost a year, should we assume this package is abandoned? (I know: send in a PR if we want to update - I'm just asking the question). No problem if so, we'll just need to work an alternative path for an L10 update. Let me know if you can - thanks.

**To Reproduce**
Try to take part in an upgrade from Laravel 9 to Laravel 10

**Expected behavior**
We're expecting to be able to nominate v4 in an upgraded L10 implementation that is being upgraded from Laravel 9, possibly run some update migrations, and begin using it again on v4.

**Screenshots**
N/a

**Desktop (please complete the following information):**
N/a

**Smartphone (please complete the following information):**
N/a

**Additional context**
N/a

**Comment by mateusjunges** [comment]
Hey 👋 sorry for the dealy in answering this. 

I'm thinking about stop maintaining this package in favor of spatie/laravel-permission. It contains basically the same features, but spatie has way more resources to maintain it than I have at the moment. 

>It looks like the DB schema is a lot different for v4, and there's no upgrade documentation to go from v3 of the package to v4.

I haven't personally tried to upgrade a project using v3 to v4 actually, but it's a lot of work to migrate the database schema, that's why I don't recommend it.
